# Enable the Pure power theme
source ~/dotfiles/zsh/purepower
source ~/dotfiles/zsh/powerlevel10k/powerlevel10k.zsh-theme

# Add the environmental variables
source /etc/profile
source ~/.profile

# Add custom user aliases
source ~/dotfiles/zsh/alias.sh


# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=10000
bindkey -e
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '/home/dvicente/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall

# Enable the Pure power theme
source ~/dotfiles/zsh/purepower
source ~/dotfiles/zsh/powerlevel10k/powerlevel10k.zsh-theme

# Add the environmental variables
source /etc/profile
source ~/.profile

# Add custom user aliases
source ~/dotfiles/zsh/alias.sh

# Activate conda
. /home/dvicente/Utilities/anaconda3/etc/profile.d/conda.sh
